// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import QuantityController from "./quantity_controller"
application.register("quantity", QuantityController)

import SelectTurboController from "./select_turbo_controller"
application.register("select-turbo", SelectTurboController)
